# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='n/a', max_length=1000),
        ),
    ]
